[package]
name = "redhook"
version = "3.0.0"
authors = ["Geoffrey Thomas <geofft@ldpreload.com>"]
description = "Dynamic function call interposition / hooking (LD_PRELOAD) for Rust"
repository = "https://github.com/geofft/redhook"
readme = "README.md"
keywords = ["LD_PRELOAD", "interposition"]
license = "BSD-2-Clause"
edition = "2021"

[features]
std = []

[dependencies]
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
once_cell = { version = "1", default-features = false, features = ["race"] }
